The configure script now can generate launch scripts for the individual GUIs similar to what it does with XGamesman. New .in templates will only get recognized with a re-run of configure. config.status may not be enough. Modified launch scripts included.
git-svn-id: https://gamescrafters.svn.sourceforge.net/svnroot/gamescrafters/GamesmanClassic/trunk@1901 a668be5d-ef11-cb4c-8bfd-e08cbb24f2ba

diff --git a/gamesman/configure b/gamesman/configure
--- a/gamesman/configure
+++ b/gamesman/configure
@@ -4308,6 +4308,177 @@ fi
 done
 
 
+###
+### An attempt to detect python
+###
+
+### go through the common locations for the header
+PYTHON_INCLUDE_PATH=""
+if test "$OS" = "MACOSX"
+then
+  _python_locations="/Library/Frameworks/Python.framework/include"
+else
+  _python_locations="/usr/include/python2.4 /usr/include/python2.3 /usr/local/include/python2.4 /usr/local/include/python2.3"
+fi
+
+for testpath in $_python_locations
+do
+  if test "$PYTHON_INCLUDE_PATH" = ""
+    then as_ac_Header=`echo "ac_cv_header_$testpath/Python.h" | $as_tr_sh`
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo "$as_me:$LINENO: checking for $testpath/Python.h" >&5
+echo $ECHO_N "checking for $testpath/Python.h... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking $testpath/Python.h usability" >&5
+echo $ECHO_N "checking $testpath/Python.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <$testpath/Python.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking $testpath/Python.h presence" >&5
+echo $ECHO_N "checking $testpath/Python.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <$testpath/Python.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+    ac_cpp_err=$ac_cpp_err$ac_c_werror_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: $testpath/Python.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: $testpath/Python.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $testpath/Python.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: $testpath/Python.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: $testpath/Python.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: $testpath/Python.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $testpath/Python.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: $testpath/Python.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $testpath/Python.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: $testpath/Python.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $testpath/Python.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: $testpath/Python.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $testpath/Python.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: $testpath/Python.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $testpath/Python.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: $testpath/Python.h: in the future, the compiler will take precedence" >&2;}
+    (
+      cat <<\_ASBOX
+## ----------------------------------- ##
+## Report this to the gamesman lists.  ##
+## ----------------------------------- ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for $testpath/Python.h" >&5
+echo $ECHO_N "checking for $testpath/Python.h... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  eval "$as_ac_Header=\$ac_header_preproc"
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
+
+fi
+if test `eval echo '${'$as_ac_Header'}'` = yes; then
+  PYTHON_INCLUDE_PATH=$testpath
+fi
+
+
+  fi
+done
+
+### see if we have it
+if test "$PYTHON_INCLUDE_PATH" = ""
+then
+  { echo "$as_me:$LINENO: WARNING: Python headers not found. You may not be able to run the python stuff here." >&5
+echo "$as_me: WARNING: Python headers not found. You may not be able to run the python stuff here." >&2;}
+else
+  OUTPYTHONCFLAGS="$OUTPYTHONCFLAGS -I$PYTHON_INCLUDE_PATH"
+fi
+
 
 
 ###
@@ -5975,178 +6146,6 @@ fi
 
 
 ###
-### An attempt to detect python
-###
-
-### go through the common locations for the header
-PYTHON_INCLUDE_PATH=""
-if test "$OS" = "MACOSX"
-then
-  _python_locations="/Library/Frameworks/Python.framework/include"
-else
-  _python_locations="/usr/include/python2.3 /usr/include/python2.4 /usr/local/include/python2.3 /usr/local/include/python2.4"
-fi
-
-for testpath in $_python_locations
-do
-  if test "$PYTHON_INCLUDE_PATH" = ""
-    then as_ac_Header=`echo "ac_cv_header_$testpath/Python.h" | $as_tr_sh`
-if eval "test \"\${$as_ac_Header+set}\" = set"; then
-  echo "$as_me:$LINENO: checking for $testpath/Python.h" >&5
-echo $ECHO_N "checking for $testpath/Python.h... $ECHO_C" >&6
-if eval "test \"\${$as_ac_Header+set}\" = set"; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-fi
-echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
-echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
-else
-  # Is the header compilable?
-echo "$as_me:$LINENO: checking $testpath/Python.h usability" >&5
-echo $ECHO_N "checking $testpath/Python.h usability... $ECHO_C" >&6
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-$ac_includes_default
-#include <$testpath/Python.h>
-_ACEOF
-rm -f conftest.$ac_objext
-if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
-  (eval $ac_compile) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest.$ac_objext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_header_compiler=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-ac_header_compiler=no
-fi
-rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
-echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
-echo "${ECHO_T}$ac_header_compiler" >&6
-
-# Is the header present?
-echo "$as_me:$LINENO: checking $testpath/Python.h presence" >&5
-echo $ECHO_N "checking $testpath/Python.h presence... $ECHO_C" >&6
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-#include <$testpath/Python.h>
-_ACEOF
-if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
-  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } >/dev/null; then
-  if test -s conftest.err; then
-    ac_cpp_err=$ac_c_preproc_warn_flag
-    ac_cpp_err=$ac_cpp_err$ac_c_werror_flag
-  else
-    ac_cpp_err=
-  fi
-else
-  ac_cpp_err=yes
-fi
-if test -z "$ac_cpp_err"; then
-  ac_header_preproc=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-  ac_header_preproc=no
-fi
-rm -f conftest.err conftest.$ac_ext
-echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
-echo "${ECHO_T}$ac_header_preproc" >&6
-
-# So?  What about this header?
-case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
-  yes:no: )
-    { echo "$as_me:$LINENO: WARNING: $testpath/Python.h: accepted by the compiler, rejected by the preprocessor!" >&5
-echo "$as_me: WARNING: $testpath/Python.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
-    { echo "$as_me:$LINENO: WARNING: $testpath/Python.h: proceeding with the compiler's result" >&5
-echo "$as_me: WARNING: $testpath/Python.h: proceeding with the compiler's result" >&2;}
-    ac_header_preproc=yes
-    ;;
-  no:yes:* )
-    { echo "$as_me:$LINENO: WARNING: $testpath/Python.h: present but cannot be compiled" >&5
-echo "$as_me: WARNING: $testpath/Python.h: present but cannot be compiled" >&2;}
-    { echo "$as_me:$LINENO: WARNING: $testpath/Python.h:     check for missing prerequisite headers?" >&5
-echo "$as_me: WARNING: $testpath/Python.h:     check for missing prerequisite headers?" >&2;}
-    { echo "$as_me:$LINENO: WARNING: $testpath/Python.h: see the Autoconf documentation" >&5
-echo "$as_me: WARNING: $testpath/Python.h: see the Autoconf documentation" >&2;}
-    { echo "$as_me:$LINENO: WARNING: $testpath/Python.h:     section \"Present But Cannot Be Compiled\"" >&5
-echo "$as_me: WARNING: $testpath/Python.h:     section \"Present But Cannot Be Compiled\"" >&2;}
-    { echo "$as_me:$LINENO: WARNING: $testpath/Python.h: proceeding with the preprocessor's result" >&5
-echo "$as_me: WARNING: $testpath/Python.h: proceeding with the preprocessor's result" >&2;}
-    { echo "$as_me:$LINENO: WARNING: $testpath/Python.h: in the future, the compiler will take precedence" >&5
-echo "$as_me: WARNING: $testpath/Python.h: in the future, the compiler will take precedence" >&2;}
-    (
-      cat <<\_ASBOX
-## ----------------------------------- ##
-## Report this to the gamesman lists.  ##
-## ----------------------------------- ##
-_ASBOX
-    ) |
-      sed "s/^/$as_me: WARNING:     /" >&2
-    ;;
-esac
-echo "$as_me:$LINENO: checking for $testpath/Python.h" >&5
-echo $ECHO_N "checking for $testpath/Python.h... $ECHO_C" >&6
-if eval "test \"\${$as_ac_Header+set}\" = set"; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  eval "$as_ac_Header=\$ac_header_preproc"
-fi
-echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
-echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
-
-fi
-if test `eval echo '${'$as_ac_Header'}'` = yes; then
-  PYTHON_INCLUDE_PATH=$testpath
-fi
-
-
-  fi
-done
-
-### see if we have it
-if test "$PYTHON_INCLUDE_PATH" = ""
-then
-  { echo "$as_me:$LINENO: WARNING: Python headers not found. You may not be able to run the python stuff here." >&5
-echo "$as_me: WARNING: Python headers not found. You may not be able to run the python stuff here." >&2;}
-else
-  OUTPYTHONCFLAGS="$OUTPYTHONCFLAGS -I$PYTHON_INCLUDE_PATH"
-fi
-
-
-###
 ### More crazy cygwin stuff
 ###
 
@@ -6197,14 +6196,17 @@ PYTHONCFLAGS=$OUTPYTHONCFLAGS
 PYTHONLIBFLAGS=$OUTPYTHONLIBFLAGS
 
 
+### get the file name for all the *.in files
+x_scripts=`ls bin/*.in | sed 's/\.in$//'`
+
 
 ###
 ### Do output
 ###
 
-                                        ac_config_files="$ac_config_files Makefile src/Makefile src/core/Makefile bin/XGamesman"
+                                        ac_config_files="$ac_config_files Makefile src/Makefile src/core/Makefile $x_scripts"
 
-          ac_config_commands="$ac_config_commands XGamesman-chmod"
+          ac_config_commands="$ac_config_commands chmod-X-scripts"
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -6319,9 +6321,10 @@ for ac_i in : $LIBOBJS; do test "x$ac_i" = x: && continue
   # 1. Remove the extension, and $U if already installed.
   ac_i=`echo "$ac_i" |
 	 sed 's/\$U\././;s/\.o$//;s/\.obj$//'`
-  # 2. Add them.
-  ac_libobjs="$ac_libobjs $ac_i\$U.$ac_objext"
-  ac_ltlibobjs="$ac_ltlibobjs $ac_i"'$U.lo'
+  # 2. Prepend LIBOBJDIR.  When used with automake>=1.10 LIBOBJDIR
+  #    will be set to the directory where LIBOBJS objects are built.
+  ac_libobjs="$ac_libobjs \${LIBOBJDIR}$ac_i\$U.$ac_objext"
+  ac_ltlibobjs="$ac_ltlibobjs \${LIBOBJDIR}$ac_i"'$U.lo'
 done
 LIBOBJS=$ac_libobjs
 
@@ -6762,8 +6765,8 @@ do
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "src/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/Makefile" ;;
   "src/core/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/core/Makefile" ;;
-  "bin/XGamesman" ) CONFIG_FILES="$CONFIG_FILES bin/XGamesman" ;;
-  "XGamesman-chmod" ) CONFIG_COMMANDS="$CONFIG_COMMANDS XGamesman-chmod" ;;
+  "$x_scripts" ) CONFIG_FILES="$CONFIG_FILES $x_scripts" ;;
+  "chmod-X-scripts" ) CONFIG_COMMANDS="$CONFIG_COMMANDS chmod-X-scripts" ;;
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
@@ -7226,7 +7229,7 @@ esac
   { echo "$as_me:$LINENO: executing $ac_dest commands" >&5
 echo "$as_me: executing $ac_dest commands" >&6;}
   case $ac_dest in
-    XGamesman-chmod ) chmod 755 bin/XGamesman ;;
+    chmod-X-scripts ) ./chmod-X-scripts ;;
   esac
 done
 _ACEOF
